/*
 * This file is part of the Silicon Labs Arduino Core
 *
 * The MIT License (MIT)
 *
 * Copyright 2024 Silicon Laboratories Inc. www.silabs.com
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

// This file is generated by ZCL Advanced Platform generator. Please don't edit manually.

// The following is brought in by the endianness component, which all
// applications must include
#include "sl_endianness.h"

#ifndef SILABS_AF_ENDPOINT_CONFIG
#define SILABS_AF_ENDPOINT_CONFIG 1

// Default values for the attributes longer than a pointer, in a form of a
// binary blob. All attribute values with size greater than 2 bytes. Excluding 0
// values and externally saved values. Separate block is generated for
// big-endian and little-endian cases.

#define ZCL_GENERATED_DEFAULTS_COUNT (5)

#if BIGENDIAN_CPU
#define ZCL_GENERATED_DEFAULTS { \
  0x09, 0xAC, 0x2F, /* 0,DEFAULT value for cluster: Green Power, attribute: gpp functionality, side: client */ \
  0xFF, 0xFF, 0xFF, /* 3,DEFAULT value for cluster: Green Power, attribute: gpp active functionality, side: client */ \
  0x5A, 0x69, 0x67, 0x42, 0x65, 0x65, 0x41, 0x6C, 0x6C, 0x69, 0x61, 0x6E, 0x63, 0x65, 0x30, 0x39, /* 6,DEFAULT value for cluster: Green Power, attribute: gp link key, side: client */ \
  0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, /* 22,DEFAULT value for cluster: Over the Air Bootloading, attribute: OTA Upgrade Server ID, side: client */ \
  0xFF, 0xFF, 0xFF, 0xFF, /* 30,DEFAULT value for cluster: Over the Air Bootloading, attribute: Offset (address) into the file, side: client */ \
}
#else //!BIGENDIAN_CPU
#define ZCL_GENERATED_DEFAULTS { \
  0x2F, 0xAC, 0x09, /* 0,DEFAULT value for cluster: Green Power, attribute: gpp functionality, side: client */ \
  0xFF, 0xFF, 0xFF, /* 3,DEFAULT value for cluster: Green Power, attribute: gpp active functionality, side: client */ \
  0x5A, 0x69, 0x67, 0x42, 0x65, 0x65, 0x41, 0x6C, 0x6C, 0x69, 0x61, 0x6E, 0x63, 0x65, 0x30, 0x39, /* 6,DEFAULT value for cluster: Green Power, attribute: gp link key, side: client */ \
  0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, /* 22,DEFAULT value for cluster: Over the Air Bootloading, attribute: OTA Upgrade Server ID, side: client */ \
  0xFF, 0xFF, 0xFF, 0xFF, /* 30,DEFAULT value for cluster: Over the Air Bootloading, attribute: Offset (address) into the file, side: client */ \
}
#endif


// This is an array of sl_zigbee_af_attribute_min_max_value_t structures.

#define ZCL_GENERATED_MIN_MAX_DEFAULT_COUNT (0)
	#define ZCL_GENERATED_MIN_MAX_DEFAULTS { }


#define ZCL_GENERATED_ATTRIBUTE_COUNT (64)

// This is an array of sl_zigbee_af_attribute_metadata_t structures.
#define ZCL_GENERATED_ATTRIBUTES { \
  { 0x0000, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_SINGLETON), { (uint8_t*)8  } }, /* 0 Cluster: Basic, Attribute: ZCL version, Side: server*/ \
		  { 0x0001, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_SINGLETON), { (uint8_t*)0  } }, /* 1 Cluster: Basic, Attribute: application version, Side: server*/ \
		  { 0x0002, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_SINGLETON), { (uint8_t*)0  } }, /* 2 Cluster: Basic, Attribute: stack version, Side: server*/ \
		  { 0x0003, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_SINGLETON), { (uint8_t*)0  } }, /* 3 Cluster: Basic, Attribute: hardware version, Side: server*/ \
		  { 0x0004, ZCL_CHAR_STRING_ATTRIBUTE_TYPE, 33, (ATTRIBUTE_MASK_SINGLETON), { (uint8_t*)0 } }, /* 4 Cluster: Basic, Attribute: manufacturer name, Side: server*/ \
	  { 0x0005, ZCL_CHAR_STRING_ATTRIBUTE_TYPE, 33, (ATTRIBUTE_MASK_SINGLETON), { (uint8_t*)0 } }, /* 5 Cluster: Basic, Attribute: model identifier, Side: server*/ \
	  { 0x0006, ZCL_CHAR_STRING_ATTRIBUTE_TYPE, 17, (ATTRIBUTE_MASK_SINGLETON), { (uint8_t*)0 } }, /* 6 Cluster: Basic, Attribute: date code, Side: server*/ \
	  { 0x0007, ZCL_ENUM8_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_SINGLETON), { (uint8_t*)0  } }, /* 7 Cluster: Basic, Attribute: power source, Side: server*/ \
		  { 0x0008, ZCL_ENUM8_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_SINGLETON), { (uint8_t*)255  } }, /* 8 Cluster: Basic, Attribute: generic device class, Side: server*/ \
		  { 0x0009, ZCL_ENUM8_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_SINGLETON), { (uint8_t*)255  } }, /* 9 Cluster: Basic, Attribute: generic device type, Side: server*/ \
		  { 0x000A, ZCL_OCTET_STRING_ATTRIBUTE_TYPE, 17, (ATTRIBUTE_MASK_SINGLETON), { (uint8_t*)0 } }, /* 10 Cluster: Basic, Attribute: product code, Side: server*/ \
	  { 0x000B, ZCL_CHAR_STRING_ATTRIBUTE_TYPE, 65, (ATTRIBUTE_MASK_SINGLETON), { (uint8_t*)0 } }, /* 11 Cluster: Basic, Attribute: product url, Side: server*/ \
	  { 0x4000, ZCL_CHAR_STRING_ATTRIBUTE_TYPE, 17, (ATTRIBUTE_MASK_SINGLETON), { (uint8_t*)0 } }, /* 12 Cluster: Basic, Attribute: sw build id, Side: server*/ \
	  { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_SINGLETON), { (uint8_t*)1  } }, /* 13 Cluster: Basic, Attribute: cluster revision, Side: server*/ \
		  { 0x0000, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE), { (uint8_t*)0  } }, /* 14 Cluster: Identify, Attribute: identify time, Side: server*/ \
		  { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (0x00), { (uint8_t*)1  } }, /* 15 Cluster: Identify, Attribute: cluster revision, Side: server*/ \
		  { 0x0000, ZCL_BITMAP8_ATTRIBUTE_TYPE, 1, (0x00), { (uint8_t*)0  } }, /* 16 Cluster: Groups, Attribute: name support, Side: server*/ \
		  { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (0x00), { (uint8_t*)1  } }, /* 17 Cluster: Groups, Attribute: cluster revision, Side: server*/ \
		  { 0x0000, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (0x00), { (uint8_t*)0  } }, /* 18 Cluster: Scenes, Attribute: scene count, Side: server*/ \
		  { 0x0001, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (0x00), { (uint8_t*)0  } }, /* 19 Cluster: Scenes, Attribute: current scene, Side: server*/ \
		  { 0x0002, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (0x00), { (uint8_t*)0  } }, /* 20 Cluster: Scenes, Attribute: current group, Side: server*/ \
		  { 0x0003, ZCL_BOOLEAN_ATTRIBUTE_TYPE, 1, (0x00), { (uint8_t*)0  } }, /* 21 Cluster: Scenes, Attribute: scene valid, Side: server*/ \
		  { 0x0004, ZCL_BITMAP8_ATTRIBUTE_TYPE, 1, (0x00), { (uint8_t*)0  } }, /* 22 Cluster: Scenes, Attribute: name support, Side: server*/ \
		  { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (0x00), { (uint8_t*)1  } }, /* 23 Cluster: Scenes, Attribute: cluster revision, Side: server*/ \
		  { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_CLIENT), { (uint8_t*)1  } }, /* 24 Cluster: On/off, Attribute: cluster revision, Side: client*/ \
		  { 0x0000, ZCL_BOOLEAN_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_TOKENIZE), { (uint8_t*)0  } }, /* 25 Cluster: On/off, Attribute: on/off, Side: server*/ \
		  { 0x4000, ZCL_BOOLEAN_ATTRIBUTE_TYPE, 1, (0x00), { (uint8_t*)1  } }, /* 26 Cluster: On/off, Attribute: global scene control, Side: server*/ \
		  { 0x4001, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE), { (uint8_t*)0  } }, /* 27 Cluster: On/off, Attribute: on time, Side: server*/ \
		  { 0x4002, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE), { (uint8_t*)0  } }, /* 28 Cluster: On/off, Attribute: off wait time, Side: server*/ \
		  { 0x4003, ZCL_ENUM8_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_TOKENIZE), { (uint8_t*)255  } }, /* 29 Cluster: On/off, Attribute: start up on off, Side: server*/ \
		  { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (0x00), { (uint8_t*)1  } }, /* 30 Cluster: On/off, Attribute: cluster revision, Side: server*/ \
		  { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_CLIENT), { (uint8_t*)1  } }, /* 31 Cluster: Level Control, Attribute: cluster revision, Side: client*/ \
		  { 0x0000, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_TOKENIZE), { (uint8_t*)0x00  } }, /* 32 Cluster: Level Control, Attribute: current level, Side: server*/ \
		  { 0x0001, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (0x00), { (uint8_t*)0x0000  } }, /* 33 Cluster: Level Control, Attribute: remaining time, Side: server*/ \
		  { 0x000F, ZCL_BITMAP8_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_WRITABLE), { (uint8_t*)0x00  } }, /* 34 Cluster: Level Control, Attribute: options, Side: server*/ \
		  { 0x0010, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE), { (uint8_t*)0x0000  } }, /* 35 Cluster: Level Control, Attribute: on off transition time, Side: server*/ \
		  { 0x0011, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_WRITABLE), { (uint8_t*)0xFE  } }, /* 36 Cluster: Level Control, Attribute: on level, Side: server*/ \
		  { 0x0014, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_WRITABLE), { (uint8_t*)0x00  } }, /* 37 Cluster: Level Control, Attribute: default move rate, Side: server*/ \
		  { 0x4000, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_TOKENIZE), { (uint8_t*)0x33  } }, /* 38 Cluster: Level Control, Attribute: start up current level, Side: server*/ \
		  { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (0x00), { (uint8_t*)0x0001  } }, /* 39 Cluster: Level Control, Attribute: cluster revision, Side: server*/ \
		  { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_CLIENT| ATTRIBUTE_MASK_SINGLETON), { (uint8_t*)2  } }, /* 40 Cluster: Time, Attribute: cluster revision, Side: client*/ \
		  { 0x0000, ZCL_IEEE_ADDRESS_ATTRIBUTE_TYPE, 8, (ATTRIBUTE_MASK_CLIENT), { (uint8_t*)&(generatedDefaults[22]) } }, /* 41 Cluster: Over the Air Bootloading, Attribute: OTA Upgrade Server ID, Side: client*/ \
	  { 0x0001, ZCL_INT32U_ATTRIBUTE_TYPE, 4, (ATTRIBUTE_MASK_CLIENT), { (uint8_t*)&(generatedDefaults[30]) } }, /* 42 Cluster: Over the Air Bootloading, Attribute: Offset (address) into the file, Side: client*/ \
	  { 0x0002, ZCL_INT32U_ATTRIBUTE_TYPE, 4, (ATTRIBUTE_MASK_CLIENT), { (uint8_t*)0 } }, /* 43 Cluster: Over the Air Bootloading, Attribute: OTA Current File Version, Side: client*/ \
	  { 0x0006, ZCL_ENUM8_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_CLIENT), { (uint8_t*)0  } }, /* 44 Cluster: Over the Air Bootloading, Attribute: OTA Upgrade Status, Side: client*/ \
		  { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_CLIENT), { (uint8_t*)1  } }, /* 45 Cluster: Over the Air Bootloading, Attribute: cluster revision, Side: client*/ \
		  { 0x0010, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_CLIENT), { (uint8_t*)0x14  } }, /* 46 Cluster: Green Power, Attribute: gpp max proxy table entries, Side: client*/ \
		  { 0x0011, ZCL_LONG_OCTET_STRING_ATTRIBUTE_TYPE, 255, (ATTRIBUTE_MASK_CLIENT), { NULL } }, /* 47 Cluster: Green Power, Attribute: proxy table, Side: client*/ \
	  { 0x0016, ZCL_BITMAP24_ATTRIBUTE_TYPE, 3, (ATTRIBUTE_MASK_CLIENT), { (uint8_t*)&(generatedDefaults[0]) } }, /* 48 Cluster: Green Power, Attribute: gpp functionality, Side: client*/ \
	  { 0x0017, ZCL_BITMAP24_ATTRIBUTE_TYPE, 3, (ATTRIBUTE_MASK_CLIENT), { (uint8_t*)&(generatedDefaults[3]) } }, /* 49 Cluster: Green Power, Attribute: gpp active functionality, Side: client*/ \
	  { 0x0020, ZCL_BITMAP8_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_CLIENT), { (uint8_t*)0x00  } }, /* 50 Cluster: Green Power, Attribute: gp shared security key type, Side: client*/ \
		  { 0x0021, ZCL_SECURITY_KEY_ATTRIBUTE_TYPE, 16, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_CLIENT), { (uint8_t*)0x00000000000000000000000000000000 } }, /* 51 Cluster: Green Power, Attribute: gp shared security key, Side: client*/ \
	  { 0x0022, ZCL_SECURITY_KEY_ATTRIBUTE_TYPE, 16, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_CLIENT), { (uint8_t*)&(generatedDefaults[6]) } }, /* 52 Cluster: Green Power, Attribute: gp link key, Side: client*/ \
	  { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_CLIENT), { (uint8_t*)0x0001  } }, /* 53 Cluster: Green Power, Attribute: cluster revision, Side: client*/ \
		  { 0x0000, ZCL_INT16S_ATTRIBUTE_TYPE, 2, (0x00), { (uint8_t*)0  } }, /* 54 Cluster: Temperature Measurement, Attribute: measured value, Side: server*/ \
		  { 0x0001, ZCL_INT16S_ATTRIBUTE_TYPE, 2, (0x00), { (uint8_t*)-27315  } }, /* 55 Cluster: Temperature Measurement, Attribute: min measured value, Side: server*/ \
		  { 0x0002, ZCL_INT16S_ATTRIBUTE_TYPE, 2, (0x00), { (uint8_t*)32767  } }, /* 56 Cluster: Temperature Measurement, Attribute: max measured value, Side: server*/ \
		  { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (0x00), { (uint8_t*)4  } }, /* 57 Cluster: Temperature Measurement, Attribute: cluster revision, Side: server*/ \
		  { 0x0000, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (0x00), { (uint8_t*)0  } }, /* 58 Cluster: Relative Humidity Measurement, Attribute: measured value, Side: server*/ \
		  { 0x0001, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (0x00), { (uint8_t*)0  } }, /* 59 Cluster: Relative Humidity Measurement, Attribute: min measured value, Side: server*/ \
		  { 0x0002, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (0x00), { (uint8_t*)10000  } }, /* 60 Cluster: Relative Humidity Measurement, Attribute: max measured value, Side: server*/ \
		  { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (0x00), { (uint8_t*)3  } }, /* 61 Cluster: Relative Humidity Measurement, Attribute: cluster revision, Side: server*/ \
		  { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_CLIENT), { (uint8_t*)1  } }, /* 62 Cluster: Occupancy Sensing, Attribute: cluster revision, Side: client*/ \
		  { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (0x00), { (uint8_t*)1  } } /* 63 Cluster: ZLL Commissioning, Attribute: cluster revision, Side: server*/ \
		 }

 

#define ZCL_GENERATED_CLUSTER_COUNT (94)
	
// This is an array of sl_zigbee_af_cluster_t structures.
#define ZCL_GENERATED_CLUSTERS { \
  { 0x0000, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[0]), 14, 0, CLUSTER_MASK_SERVER, NULL }, /* 0, Endpoint Id: 1, Cluster: Basic, Side: server*/ \
	  { 0x0003, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[14]), 2, 4, CLUSTER_MASK_SERVER, NULL }, /* 1, Endpoint Id: 1, Cluster: Identify, Side: server*/ \
	  { 0x0004, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[16]), 2, 3, CLUSTER_MASK_SERVER, NULL }, /* 2, Endpoint Id: 1, Cluster: Groups, Side: server*/ \
	  { 0x0005, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[18]), 6, 8, CLUSTER_MASK_SERVER, NULL }, /* 3, Endpoint Id: 1, Cluster: Scenes, Side: server*/ \
	  { 0x0006, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[25]), 6, 9, CLUSTER_MASK_SERVER, NULL }, /* 4, Endpoint Id: 1, Cluster: On/off, Side: server*/ \
	  { 0x0019, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[41]), 5, 19, CLUSTER_MASK_CLIENT, NULL }, /* 5, Endpoint Id: 1, Cluster: Over the Air Bootloading, Side: client*/ \
	  { 0x0406, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[62]), 1, 2, CLUSTER_MASK_CLIENT, NULL }, /* 6, Endpoint Id: 1, Cluster: Occupancy Sensing, Side: client*/ \
	  { 0x1000, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[63]), 1, 2, CLUSTER_MASK_SERVER, NULL }, /* 7, Endpoint Id: 1, Cluster: ZLL Commissioning, Side: server*/ \
	  { 0x0000, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[0]), 14, 0, CLUSTER_MASK_SERVER, NULL }, /* 8, Endpoint Id: 2, Cluster: Basic, Side: server*/ \
	  { 0x0003, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[14]), 2, 4, CLUSTER_MASK_SERVER, NULL }, /* 9, Endpoint Id: 2, Cluster: Identify, Side: server*/ \
	  { 0x0004, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[16]), 2, 3, CLUSTER_MASK_SERVER, NULL }, /* 10, Endpoint Id: 2, Cluster: Groups, Side: server*/ \
	  { 0x0005, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[18]), 6, 8, CLUSTER_MASK_SERVER, NULL }, /* 11, Endpoint Id: 2, Cluster: Scenes, Side: server*/ \
	  { 0x0006, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[25]), 6, 9, CLUSTER_MASK_SERVER, NULL }, /* 12, Endpoint Id: 2, Cluster: On/off, Side: server*/ \
	  { 0x0019, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[41]), 5, 19, CLUSTER_MASK_CLIENT, NULL }, /* 13, Endpoint Id: 2, Cluster: Over the Air Bootloading, Side: client*/ \
	  { 0x0406, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[62]), 1, 2, CLUSTER_MASK_CLIENT, NULL }, /* 14, Endpoint Id: 2, Cluster: Occupancy Sensing, Side: client*/ \
	  { 0x1000, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[63]), 1, 2, CLUSTER_MASK_SERVER, NULL }, /* 15, Endpoint Id: 2, Cluster: ZLL Commissioning, Side: server*/ \
	  { 0x0000, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[0]), 14, 0, CLUSTER_MASK_SERVER, NULL }, /* 16, Endpoint Id: 3, Cluster: Basic, Side: server*/ \
	  { 0x0003, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[14]), 2, 4, CLUSTER_MASK_SERVER, NULL }, /* 17, Endpoint Id: 3, Cluster: Identify, Side: server*/ \
	  { 0x0004, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[16]), 2, 3, CLUSTER_MASK_SERVER, NULL }, /* 18, Endpoint Id: 3, Cluster: Groups, Side: server*/ \
	  { 0x0005, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[18]), 6, 8, CLUSTER_MASK_SERVER, NULL }, /* 19, Endpoint Id: 3, Cluster: Scenes, Side: server*/ \
	  { 0x0006, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[25]), 6, 9, CLUSTER_MASK_SERVER, NULL }, /* 20, Endpoint Id: 3, Cluster: On/off, Side: server*/ \
	  { 0x0019, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[41]), 5, 19, CLUSTER_MASK_CLIENT, NULL }, /* 21, Endpoint Id: 3, Cluster: Over the Air Bootloading, Side: client*/ \
	  { 0x0406, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[62]), 1, 2, CLUSTER_MASK_CLIENT, NULL }, /* 22, Endpoint Id: 3, Cluster: Occupancy Sensing, Side: client*/ \
	  { 0x1000, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[63]), 1, 2, CLUSTER_MASK_SERVER, NULL }, /* 23, Endpoint Id: 3, Cluster: ZLL Commissioning, Side: server*/ \
	  { 0x0000, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[0]), 14, 0, CLUSTER_MASK_SERVER, NULL }, /* 24, Endpoint Id: 4, Cluster: Basic, Side: server*/ \
	  { 0x0003, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[14]), 2, 4, CLUSTER_MASK_SERVER, NULL }, /* 25, Endpoint Id: 4, Cluster: Identify, Side: server*/ \
	  { 0x0019, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[41]), 5, 19, CLUSTER_MASK_CLIENT, NULL }, /* 26, Endpoint Id: 4, Cluster: Over the Air Bootloading, Side: client*/ \
	  { 0x0402, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[54]), 4, 8, CLUSTER_MASK_SERVER, NULL }, /* 27, Endpoint Id: 4, Cluster: Temperature Measurement, Side: server*/ \
	  { 0x0000, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[0]), 14, 0, CLUSTER_MASK_SERVER, NULL }, /* 28, Endpoint Id: 5, Cluster: Basic, Side: server*/ \
	  { 0x0003, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[14]), 2, 4, CLUSTER_MASK_SERVER, NULL }, /* 29, Endpoint Id: 5, Cluster: Identify, Side: server*/ \
	  { 0x0019, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[41]), 5, 19, CLUSTER_MASK_CLIENT, NULL }, /* 30, Endpoint Id: 5, Cluster: Over the Air Bootloading, Side: client*/ \
	  { 0x0402, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[54]), 4, 8, CLUSTER_MASK_SERVER, NULL }, /* 31, Endpoint Id: 5, Cluster: Temperature Measurement, Side: server*/ \
	  { 0x0000, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[0]), 14, 0, CLUSTER_MASK_SERVER, NULL }, /* 32, Endpoint Id: 6, Cluster: Basic, Side: server*/ \
	  { 0x0003, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[14]), 2, 4, CLUSTER_MASK_SERVER, NULL }, /* 33, Endpoint Id: 6, Cluster: Identify, Side: server*/ \
	  { 0x0019, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[41]), 5, 19, CLUSTER_MASK_CLIENT, NULL }, /* 34, Endpoint Id: 6, Cluster: Over the Air Bootloading, Side: client*/ \
	  { 0x0402, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[54]), 4, 8, CLUSTER_MASK_SERVER, NULL }, /* 35, Endpoint Id: 6, Cluster: Temperature Measurement, Side: server*/ \
	  { 0x0000, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[0]), 14, 0, CLUSTER_MASK_SERVER, NULL }, /* 36, Endpoint Id: 7, Cluster: Basic, Side: server*/ \
	  { 0x0003, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[14]), 2, 4, CLUSTER_MASK_SERVER, NULL }, /* 37, Endpoint Id: 7, Cluster: Identify, Side: server*/ \
	  { 0x0019, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[41]), 5, 19, CLUSTER_MASK_CLIENT, NULL }, /* 38, Endpoint Id: 7, Cluster: Over the Air Bootloading, Side: client*/ \
	  { 0x0405, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[58]), 4, 8, CLUSTER_MASK_SERVER, NULL }, /* 39, Endpoint Id: 7, Cluster: Relative Humidity Measurement, Side: server*/ \
	  { 0x0000, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[0]), 14, 0, CLUSTER_MASK_SERVER, NULL }, /* 40, Endpoint Id: 8, Cluster: Basic, Side: server*/ \
	  { 0x0003, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[14]), 2, 4, CLUSTER_MASK_SERVER, NULL }, /* 41, Endpoint Id: 8, Cluster: Identify, Side: server*/ \
	  { 0x0019, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[41]), 5, 19, CLUSTER_MASK_CLIENT, NULL }, /* 42, Endpoint Id: 8, Cluster: Over the Air Bootloading, Side: client*/ \
	  { 0x0405, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[58]), 4, 8, CLUSTER_MASK_SERVER, NULL }, /* 43, Endpoint Id: 8, Cluster: Relative Humidity Measurement, Side: server*/ \
	  { 0x0000, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[0]), 14, 0, CLUSTER_MASK_SERVER, NULL }, /* 44, Endpoint Id: 9, Cluster: Basic, Side: server*/ \
	  { 0x0003, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[14]), 2, 4, CLUSTER_MASK_SERVER, NULL }, /* 45, Endpoint Id: 9, Cluster: Identify, Side: server*/ \
	  { 0x0019, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[41]), 5, 19, CLUSTER_MASK_CLIENT, NULL }, /* 46, Endpoint Id: 9, Cluster: Over the Air Bootloading, Side: client*/ \
	  { 0x0405, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[58]), 4, 8, CLUSTER_MASK_SERVER, NULL }, /* 47, Endpoint Id: 9, Cluster: Relative Humidity Measurement, Side: server*/ \
	  { 0x0000, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[0]), 14, 0, CLUSTER_MASK_SERVER, NULL }, /* 48, Endpoint Id: 10, Cluster: Basic, Side: server*/ \
	  { 0x0003, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[14]), 2, 4, CLUSTER_MASK_SERVER, NULL }, /* 49, Endpoint Id: 10, Cluster: Identify, Side: server*/ \
	  { 0x0006, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[24]), 1, 2, CLUSTER_MASK_CLIENT, NULL }, /* 50, Endpoint Id: 10, Cluster: On/off, Side: client*/ \
	  { 0x0008, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[31]), 1, 2, CLUSTER_MASK_CLIENT, NULL }, /* 51, Endpoint Id: 10, Cluster: Level Control, Side: client*/ \
	  { 0x0019, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[41]), 5, 19, CLUSTER_MASK_CLIENT, NULL }, /* 52, Endpoint Id: 10, Cluster: Over the Air Bootloading, Side: client*/ \
	  { 0x0000, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[0]), 14, 0, CLUSTER_MASK_SERVER, NULL }, /* 53, Endpoint Id: 11, Cluster: Basic, Side: server*/ \
	  { 0x0003, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[14]), 2, 4, CLUSTER_MASK_SERVER, NULL }, /* 54, Endpoint Id: 11, Cluster: Identify, Side: server*/ \
	  { 0x0006, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[24]), 1, 2, CLUSTER_MASK_CLIENT, NULL }, /* 55, Endpoint Id: 11, Cluster: On/off, Side: client*/ \
	  { 0x0008, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[31]), 1, 2, CLUSTER_MASK_CLIENT, NULL }, /* 56, Endpoint Id: 11, Cluster: Level Control, Side: client*/ \
	  { 0x0019, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[41]), 5, 19, CLUSTER_MASK_CLIENT, NULL }, /* 57, Endpoint Id: 11, Cluster: Over the Air Bootloading, Side: client*/ \
	  { 0x0000, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[0]), 14, 0, CLUSTER_MASK_SERVER, NULL }, /* 58, Endpoint Id: 12, Cluster: Basic, Side: server*/ \
	  { 0x0003, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[14]), 2, 4, CLUSTER_MASK_SERVER, NULL }, /* 59, Endpoint Id: 12, Cluster: Identify, Side: server*/ \
	  { 0x0006, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[24]), 1, 2, CLUSTER_MASK_CLIENT, NULL }, /* 60, Endpoint Id: 12, Cluster: On/off, Side: client*/ \
	  { 0x0008, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[31]), 1, 2, CLUSTER_MASK_CLIENT, NULL }, /* 61, Endpoint Id: 12, Cluster: Level Control, Side: client*/ \
	  { 0x0019, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[41]), 5, 19, CLUSTER_MASK_CLIENT, NULL }, /* 62, Endpoint Id: 12, Cluster: Over the Air Bootloading, Side: client*/ \
	  { 0x0000, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[0]), 14, 0, CLUSTER_MASK_SERVER, NULL }, /* 63, Endpoint Id: 13, Cluster: Basic, Side: server*/ \
	  { 0x0003, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[14]), 2, 4, CLUSTER_MASK_SERVER, NULL }, /* 64, Endpoint Id: 13, Cluster: Identify, Side: server*/ \
	  { 0x0004, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[16]), 2, 3, CLUSTER_MASK_SERVER, NULL }, /* 65, Endpoint Id: 13, Cluster: Groups, Side: server*/ \
	  { 0x0005, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[18]), 6, 8, CLUSTER_MASK_SERVER, NULL }, /* 66, Endpoint Id: 13, Cluster: Scenes, Side: server*/ \
	  { 0x0006, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[25]), 6, 9, CLUSTER_MASK_SERVER, NULL }, /* 67, Endpoint Id: 13, Cluster: On/off, Side: server*/ \
	  { 0x0008, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[32]), 8, 11, CLUSTER_MASK_SERVER, NULL }, /* 68, Endpoint Id: 13, Cluster: Level Control, Side: server*/ \
	  { 0x0019, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[41]), 5, 19, CLUSTER_MASK_CLIENT, NULL }, /* 69, Endpoint Id: 13, Cluster: Over the Air Bootloading, Side: client*/ \
	  { 0x0406, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[62]), 1, 2, CLUSTER_MASK_CLIENT, NULL }, /* 70, Endpoint Id: 13, Cluster: Occupancy Sensing, Side: client*/ \
	  { 0x1000, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[63]), 1, 2, CLUSTER_MASK_SERVER, NULL }, /* 71, Endpoint Id: 13, Cluster: ZLL Commissioning, Side: server*/ \
	  { 0x0000, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[0]), 14, 0, CLUSTER_MASK_SERVER, NULL }, /* 72, Endpoint Id: 14, Cluster: Basic, Side: server*/ \
	  { 0x0003, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[14]), 2, 4, CLUSTER_MASK_SERVER, NULL }, /* 73, Endpoint Id: 14, Cluster: Identify, Side: server*/ \
	  { 0x0004, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[16]), 2, 3, CLUSTER_MASK_SERVER, NULL }, /* 74, Endpoint Id: 14, Cluster: Groups, Side: server*/ \
	  { 0x0005, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[18]), 6, 8, CLUSTER_MASK_SERVER, NULL }, /* 75, Endpoint Id: 14, Cluster: Scenes, Side: server*/ \
	  { 0x0006, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[25]), 6, 9, CLUSTER_MASK_SERVER, NULL }, /* 76, Endpoint Id: 14, Cluster: On/off, Side: server*/ \
	  { 0x0008, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[32]), 8, 11, CLUSTER_MASK_SERVER, NULL }, /* 77, Endpoint Id: 14, Cluster: Level Control, Side: server*/ \
	  { 0x0019, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[41]), 5, 19, CLUSTER_MASK_CLIENT, NULL }, /* 78, Endpoint Id: 14, Cluster: Over the Air Bootloading, Side: client*/ \
	  { 0x0406, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[62]), 1, 2, CLUSTER_MASK_CLIENT, NULL }, /* 79, Endpoint Id: 14, Cluster: Occupancy Sensing, Side: client*/ \
	  { 0x1000, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[63]), 1, 2, CLUSTER_MASK_SERVER, NULL }, /* 80, Endpoint Id: 14, Cluster: ZLL Commissioning, Side: server*/ \
	  { 0x0000, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[0]), 14, 0, CLUSTER_MASK_SERVER, NULL }, /* 81, Endpoint Id: 15, Cluster: Basic, Side: server*/ \
	  { 0x0003, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[14]), 2, 4, CLUSTER_MASK_SERVER, NULL }, /* 82, Endpoint Id: 15, Cluster: Identify, Side: server*/ \
	  { 0x0004, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[16]), 2, 3, CLUSTER_MASK_SERVER, NULL }, /* 83, Endpoint Id: 15, Cluster: Groups, Side: server*/ \
	  { 0x0005, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[18]), 6, 8, CLUSTER_MASK_SERVER, NULL }, /* 84, Endpoint Id: 15, Cluster: Scenes, Side: server*/ \
	  { 0x0006, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[25]), 6, 9, CLUSTER_MASK_SERVER, NULL }, /* 85, Endpoint Id: 15, Cluster: On/off, Side: server*/ \
	  { 0x0008, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[32]), 8, 11, CLUSTER_MASK_SERVER, NULL }, /* 86, Endpoint Id: 15, Cluster: Level Control, Side: server*/ \
	  { 0x0019, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[41]), 5, 19, CLUSTER_MASK_CLIENT, NULL }, /* 87, Endpoint Id: 15, Cluster: Over the Air Bootloading, Side: client*/ \
	  { 0x0406, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[62]), 1, 2, CLUSTER_MASK_CLIENT, NULL }, /* 88, Endpoint Id: 15, Cluster: Occupancy Sensing, Side: client*/ \
	  { 0x1000, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[63]), 1, 2, CLUSTER_MASK_SERVER, NULL }, /* 89, Endpoint Id: 15, Cluster: ZLL Commissioning, Side: server*/ \
	  { 0x0000, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[0]), 14, 0, CLUSTER_MASK_SERVER, NULL }, /* 90, Endpoint Id: 240, Cluster: Basic, Side: server*/ \
	  { 0x0003, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[14]), 2, 4, CLUSTER_MASK_SERVER, NULL }, /* 91, Endpoint Id: 240, Cluster: Identify, Side: server*/ \
	  { 0x000A, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[40]), 1, 0, CLUSTER_MASK_CLIENT, NULL }, /* 92, Endpoint Id: 240, Cluster: Time, Side: client*/ \
	  { 0x0021, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[46]), 8, 297, CLUSTER_MASK_CLIENT, NULL } /* 93, Endpoint Id: 242, Cluster: Green Power, Side: client*/ \
	 }

 
#define ZCL_GENERATED_ENDPOINT_TYPE_COUNT (17)

// This is an array of sl_zigbee_af_endpoint_type_t structures.
#define ZCL_GENERATED_ENDPOINT_TYPES { \
  { ((sl_zigbee_af_cluster_t*)&(generatedClusters[0])), 8, 47 }, \
	  { ((sl_zigbee_af_cluster_t*)&(generatedClusters[8])), 8, 47 }, \
	  { ((sl_zigbee_af_cluster_t*)&(generatedClusters[16])), 8, 47 }, \
	  { ((sl_zigbee_af_cluster_t*)&(generatedClusters[24])), 4, 31 }, \
	  { ((sl_zigbee_af_cluster_t*)&(generatedClusters[28])), 4, 31 }, \
	  { ((sl_zigbee_af_cluster_t*)&(generatedClusters[32])), 4, 31 }, \
	  { ((sl_zigbee_af_cluster_t*)&(generatedClusters[36])), 4, 31 }, \
	  { ((sl_zigbee_af_cluster_t*)&(generatedClusters[40])), 4, 31 }, \
	  { ((sl_zigbee_af_cluster_t*)&(generatedClusters[44])), 4, 31 }, \
	  { ((sl_zigbee_af_cluster_t*)&(generatedClusters[48])), 5, 27 }, \
	  { ((sl_zigbee_af_cluster_t*)&(generatedClusters[53])), 5, 27 }, \
	  { ((sl_zigbee_af_cluster_t*)&(generatedClusters[58])), 5, 27 }, \
	  { ((sl_zigbee_af_cluster_t*)&(generatedClusters[63])), 9, 58 }, \
	  { ((sl_zigbee_af_cluster_t*)&(generatedClusters[72])), 9, 58 }, \
	  { ((sl_zigbee_af_cluster_t*)&(generatedClusters[81])), 9, 58 }, \
	  { ((sl_zigbee_af_cluster_t*)&(generatedClusters[90])), 3, 4 }, \
	  { ((sl_zigbee_af_cluster_t*)&(generatedClusters[93])), 1, 297 }, \
	 } 
// Largest attribute size is needed for various buffers
#define ZCL_ATTRIBUTE_LARGEST (255)

// Total size of singleton attributes
#define ZCL_ATTRIBUTE_SINGLETONS_SIZE (193)

// Total size of attribute storage
#define ZCL_ATTRIBUTE_MAX_SIZE (883)

// Number of fixed endpoints	
#define ZCL_FIXED_ENDPOINT_COUNT (17)

// Array of endpoints that are supported, the data inside the array is the
// endpoint number.
#define ZCL_FIXED_ENDPOINT_ARRAY { \
  1, \
  2, \
  3, \
  4, \
  5, \
  6, \
  7, \
  8, \
  9, \
  10, \
  11, \
  12, \
  13, \
  14, \
  15, \
  240, \
  242 \
}

// Array of profile ids
#define ZCL_FIXED_PROFILE_IDS { \
  260, \
  260, \
  260, \
  260, \
  260, \
  260, \
  260, \
  260, \
  260, \
  260, \
  260, \
  260, \
  260, \
  260, \
  260, \
  260, \
  41440 \
}

// Array of device ids
#define ZCL_FIXED_DEVICE_IDS { \
  256, \
  256, \
  256, \
  770, \
  770, \
  770, \
  770, \
  770, \
  770, \
  259, \
  259, \
  259, \
  257, \
  257, \
  257, \
  5, \
  97 \
}

// Array of device versions
#define ZCL_FIXED_DEVICE_VERSIONS { \
  1, \
  1, \
  1, \
  1, \
  1, \
  1, \
  1, \
  1, \
  1, \
  1, \
  1, \
  1, \
  1, \
  1, \
  1, \
  1, \
  0 \
}

// Array of endpoint types supported on each endpoint
#define ZCL_FIXED_ENDPOINT_TYPES { \
  0, \
  1, \
  2, \
  3, \
  4, \
  5, \
  6, \
  7, \
  8, \
  9, \
  10, \
  11, \
  12, \
  13, \
  14, \
  15, \
  16 \
}

// Array of networks supported on each endpoint
#define ZCL_FIXED_NETWORKS { \
  0, \
  0, \
  0, \
  0, \
  0, \
  0, \
  0, \
  0, \
  0, \
  0, \
  0, \
  0, \
  0, \
  0, \
  0, \
  0, \
  0 \
}

// Array of sl_zigbee_af_command_metadata_t structs.
#define ZCL_ZAP_COMMAND_MASK(mask) COMMAND_MASK_ ## mask
#define SL_ZIGBEE_ZCL_GENERATED_COMMAND_COUNT  (74)
#define ZCL_GENERATED_COMMANDS { \
  { 0x0000, 0x00, COMMAND_MASK_INCOMING_SERVER }, /* 0, Cluster: Basic, Command: ResetToFactoryDefaults*/ \
	  { 0x0003, 0x00, COMMAND_MASK_INCOMING_SERVER }, /* 1, Cluster: Identify, Command: Identify*/ \
	  { 0x0003, 0x00, COMMAND_MASK_OUTGOING_SERVER }, /* 2, Cluster: Identify, Command: IdentifyQueryResponse*/ \
	  { 0x0003, 0x01, COMMAND_MASK_INCOMING_SERVER }, /* 3, Cluster: Identify, Command: IdentifyQuery*/ \
	  { 0x0003, 0x40, COMMAND_MASK_INCOMING_SERVER }, /* 4, Cluster: Identify, Command: TriggerEffect*/ \
	  { 0x0004, 0x00, COMMAND_MASK_INCOMING_SERVER }, /* 5, Cluster: Groups, Command: AddGroup*/ \
	  { 0x0004, 0x00, COMMAND_MASK_OUTGOING_SERVER }, /* 6, Cluster: Groups, Command: AddGroupResponse*/ \
	  { 0x0004, 0x01, COMMAND_MASK_INCOMING_SERVER }, /* 7, Cluster: Groups, Command: ViewGroup*/ \
	  { 0x0004, 0x01, COMMAND_MASK_OUTGOING_SERVER }, /* 8, Cluster: Groups, Command: ViewGroupResponse*/ \
	  { 0x0004, 0x02, COMMAND_MASK_INCOMING_SERVER }, /* 9, Cluster: Groups, Command: GetGroupMembership*/ \
	  { 0x0004, 0x02, COMMAND_MASK_OUTGOING_SERVER }, /* 10, Cluster: Groups, Command: GetGroupMembershipResponse*/ \
	  { 0x0004, 0x03, COMMAND_MASK_INCOMING_SERVER }, /* 11, Cluster: Groups, Command: RemoveGroup*/ \
	  { 0x0004, 0x03, COMMAND_MASK_OUTGOING_SERVER }, /* 12, Cluster: Groups, Command: RemoveGroupResponse*/ \
	  { 0x0004, 0x04, COMMAND_MASK_INCOMING_SERVER }, /* 13, Cluster: Groups, Command: RemoveAllGroups*/ \
	  { 0x0004, 0x05, COMMAND_MASK_INCOMING_SERVER }, /* 14, Cluster: Groups, Command: AddGroupIfIdentifying*/ \
	  { 0x0005, 0x00, COMMAND_MASK_INCOMING_SERVER }, /* 15, Cluster: Scenes, Command: AddScene*/ \
	  { 0x0005, 0x00, COMMAND_MASK_OUTGOING_SERVER }, /* 16, Cluster: Scenes, Command: AddSceneResponse*/ \
	  { 0x0005, 0x01, COMMAND_MASK_INCOMING_SERVER }, /* 17, Cluster: Scenes, Command: ViewScene*/ \
	  { 0x0005, 0x01, COMMAND_MASK_OUTGOING_SERVER }, /* 18, Cluster: Scenes, Command: ViewSceneResponse*/ \
	  { 0x0005, 0x02, COMMAND_MASK_INCOMING_SERVER }, /* 19, Cluster: Scenes, Command: RemoveScene*/ \
	  { 0x0005, 0x02, COMMAND_MASK_OUTGOING_SERVER }, /* 20, Cluster: Scenes, Command: RemoveSceneResponse*/ \
	  { 0x0005, 0x03, COMMAND_MASK_INCOMING_SERVER }, /* 21, Cluster: Scenes, Command: RemoveAllScenes*/ \
	  { 0x0005, 0x03, COMMAND_MASK_OUTGOING_SERVER }, /* 22, Cluster: Scenes, Command: RemoveAllScenesResponse*/ \
	  { 0x0005, 0x04, COMMAND_MASK_INCOMING_SERVER }, /* 23, Cluster: Scenes, Command: StoreScene*/ \
	  { 0x0005, 0x04, COMMAND_MASK_OUTGOING_SERVER }, /* 24, Cluster: Scenes, Command: StoreSceneResponse*/ \
	  { 0x0005, 0x05, COMMAND_MASK_INCOMING_SERVER }, /* 25, Cluster: Scenes, Command: RecallScene*/ \
	  { 0x0005, 0x06, COMMAND_MASK_INCOMING_SERVER }, /* 26, Cluster: Scenes, Command: GetSceneMembership*/ \
	  { 0x0005, 0x06, COMMAND_MASK_OUTGOING_SERVER }, /* 27, Cluster: Scenes, Command: GetSceneMembershipResponse*/ \
	  { 0x0005, 0x40, COMMAND_MASK_INCOMING_SERVER }, /* 28, Cluster: Scenes, Command: EnhancedAddScene*/ \
	  { 0x0005, 0x41, COMMAND_MASK_INCOMING_SERVER }, /* 29, Cluster: Scenes, Command: EnhancedViewScene*/ \
	  { 0x0005, 0x42, COMMAND_MASK_INCOMING_SERVER }, /* 30, Cluster: Scenes, Command: CopyScene*/ \
	  { 0x0006, 0x00, COMMAND_MASK_INCOMING_SERVER }, /* 31, Cluster: On/off, Command: Off*/ \
	  { 0x0006, 0x01, COMMAND_MASK_INCOMING_SERVER }, /* 32, Cluster: On/off, Command: On*/ \
	  { 0x0006, 0x02, COMMAND_MASK_INCOMING_SERVER }, /* 33, Cluster: On/off, Command: Toggle*/ \
	  { 0x0006, 0x40, COMMAND_MASK_INCOMING_SERVER }, /* 34, Cluster: On/off, Command: OffWithEffect*/ \
	  { 0x0006, 0x41, COMMAND_MASK_INCOMING_SERVER }, /* 35, Cluster: On/off, Command: OnWithRecallGlobalScene*/ \
	  { 0x0006, 0x42, COMMAND_MASK_INCOMING_SERVER }, /* 36, Cluster: On/off, Command: OnWithTimedOff*/ \
	  { 0x0008, 0x00, COMMAND_MASK_INCOMING_SERVER }, /* 37, Cluster: Level Control, Command: MoveToLevel*/ \
	  { 0x0008, 0x01, COMMAND_MASK_INCOMING_SERVER }, /* 38, Cluster: Level Control, Command: Move*/ \
	  { 0x0008, 0x02, COMMAND_MASK_INCOMING_SERVER }, /* 39, Cluster: Level Control, Command: Step*/ \
	  { 0x0008, 0x03, COMMAND_MASK_INCOMING_SERVER }, /* 40, Cluster: Level Control, Command: Stop*/ \
	  { 0x0008, 0x04, COMMAND_MASK_INCOMING_SERVER }, /* 41, Cluster: Level Control, Command: MoveToLevelWithOnOff*/ \
	  { 0x0008, 0x05, COMMAND_MASK_INCOMING_SERVER }, /* 42, Cluster: Level Control, Command: MoveWithOnOff*/ \
	  { 0x0008, 0x06, COMMAND_MASK_INCOMING_SERVER }, /* 43, Cluster: Level Control, Command: StepWithOnOff*/ \
	  { 0x0008, 0x07, COMMAND_MASK_INCOMING_SERVER }, /* 44, Cluster: Level Control, Command: StopWithOnOff*/ \
	  { 0x0019, 0x00, COMMAND_MASK_INCOMING_CLIENT }, /* 45, Cluster: Over the Air Bootloading, Command: ImageNotify*/ \
	  { 0x0019, 0x01, COMMAND_MASK_OUTGOING_CLIENT }, /* 46, Cluster: Over the Air Bootloading, Command: QueryNextImageRequest*/ \
	  { 0x0019, 0x02, COMMAND_MASK_INCOMING_CLIENT }, /* 47, Cluster: Over the Air Bootloading, Command: QueryNextImageResponse*/ \
	  { 0x0019, 0x03, COMMAND_MASK_OUTGOING_CLIENT }, /* 48, Cluster: Over the Air Bootloading, Command: ImageBlockRequest*/ \
	  { 0x0019, 0x05, COMMAND_MASK_INCOMING_CLIENT }, /* 49, Cluster: Over the Air Bootloading, Command: ImageBlockResponse*/ \
	  { 0x0019, 0x06, COMMAND_MASK_OUTGOING_CLIENT }, /* 50, Cluster: Over the Air Bootloading, Command: UpgradeEndRequest*/ \
	  { 0x0019, 0x07, COMMAND_MASK_INCOMING_CLIENT }, /* 51, Cluster: Over the Air Bootloading, Command: UpgradeEndResponse*/ \
	  { 0x0021, 0x01, COMMAND_MASK_INCOMING_CLIENT }, /* 52, Cluster: Green Power, Command: GpPairing*/ \
	  { 0x0021, 0x02, COMMAND_MASK_INCOMING_CLIENT }, /* 53, Cluster: Green Power, Command: GpProxyCommissioningMode*/ \
	  { 0x0021, 0x06, COMMAND_MASK_INCOMING_CLIENT }, /* 54, Cluster: Green Power, Command: GpResponse*/ \
	  { 0x0021, 0x0B, COMMAND_MASK_INCOMING_CLIENT }, /* 55, Cluster: Green Power, Command: GpProxyTableRequest*/ \
	  { 0x1000, 0x00, COMMAND_MASK_INCOMING_SERVER }, /* 56, Cluster: ZLL Commissioning, Command: ScanRequest*/ \
	  { 0x1000, 0x01, COMMAND_MASK_OUTGOING_SERVER }, /* 57, Cluster: ZLL Commissioning, Command: ScanResponse*/ \
	  { 0x1000, 0x02, COMMAND_MASK_INCOMING_SERVER }, /* 58, Cluster: ZLL Commissioning, Command: DeviceInformationRequest*/ \
	  { 0x1000, 0x03, COMMAND_MASK_OUTGOING_SERVER }, /* 59, Cluster: ZLL Commissioning, Command: DeviceInformationResponse*/ \
	  { 0x1000, 0x06, COMMAND_MASK_INCOMING_SERVER }, /* 60, Cluster: ZLL Commissioning, Command: IdentifyRequest*/ \
	  { 0x1000, 0x07, COMMAND_MASK_INCOMING_SERVER }, /* 61, Cluster: ZLL Commissioning, Command: ResetToFactoryNewRequest*/ \
	  { 0x1000, 0x10, COMMAND_MASK_INCOMING_SERVER }, /* 62, Cluster: ZLL Commissioning, Command: NetworkStartRequest*/ \
	  { 0x1000, 0x11, COMMAND_MASK_OUTGOING_SERVER }, /* 63, Cluster: ZLL Commissioning, Command: NetworkStartResponse*/ \
	  { 0x1000, 0x12, COMMAND_MASK_INCOMING_SERVER }, /* 64, Cluster: ZLL Commissioning, Command: NetworkJoinRouterRequest*/ \
	  { 0x1000, 0x13, COMMAND_MASK_OUTGOING_SERVER }, /* 65, Cluster: ZLL Commissioning, Command: NetworkJoinRouterResponse*/ \
	  { 0x1000, 0x14, COMMAND_MASK_INCOMING_SERVER }, /* 66, Cluster: ZLL Commissioning, Command: NetworkJoinEndDeviceRequest*/ \
	  { 0x1000, 0x15, COMMAND_MASK_OUTGOING_SERVER }, /* 67, Cluster: ZLL Commissioning, Command: NetworkJoinEndDeviceResponse*/ \
	  { 0x1000, 0x16, COMMAND_MASK_INCOMING_SERVER }, /* 68, Cluster: ZLL Commissioning, Command: NetworkUpdateRequest*/ \
	  { 0x1000, 0x40, COMMAND_MASK_OUTGOING_SERVER }, /* 69, Cluster: ZLL Commissioning, Command: EndpointInformation*/ \
	  { 0x1000, 0x41, COMMAND_MASK_INCOMING_SERVER }, /* 70, Cluster: ZLL Commissioning, Command: GetGroupIdentifiersRequest*/ \
	  { 0x1000, 0x41, COMMAND_MASK_OUTGOING_SERVER }, /* 71, Cluster: ZLL Commissioning, Command: GetGroupIdentifiersResponse*/ \
	  { 0x1000, 0x42, COMMAND_MASK_INCOMING_SERVER }, /* 72, Cluster: ZLL Commissioning, Command: GetEndpointListRequest*/ \
	  { 0x1000, 0x42, COMMAND_MASK_OUTGOING_SERVER }, /* 73, Cluster: ZLL Commissioning, Command: GetEndpointListResponse*/ \
	 } 
// Array of sl_zigbee_af_manufacturer_code_entry_t structures for commands.
#define ZCL_GENERATED_COMMAND_MANUFACTURER_CODE_COUNT (0)
#define ZCL_GENERATED_COMMAND_MANUFACTURER_CODES { \
  { 0x00, 0x00 }  \
																																																																										 } 
// This is an array of sl_zigbee_af_manufacturer_code_entry_t structures for clusters.
#define ZCL_GENERATED_CLUSTER_MANUFACTURER_CODE_COUNT (0)
#define ZCL_GENERATED_CLUSTER_MANUFACTURER_CODES { \
  { 0x00, 0x00 }  \
																																																																																														 } 
// This is an array of sl_zigbee_af_manufacturer_code_entry_t structures for attributes.
#define ZCL_GENERATED_ATTRIBUTE_MANUFACTURER_CODE_COUNT (0)
#define ZCL_GENERATED_ATTRIBUTE_MANUFACTURER_CODES { \
  { 0x00, 0x00 } \
																																																																 } 
// Array of sl_zigbee_af_plugin_reporting_entry_t structures.
#define SL_ZIGBEE_ZCL_GENERATED_REPORTING_CONFIG_DEFAULTS_TABLE_SIZE (33)
#define SL_ZIGBEE_ZCL_GENERATED_REPORTING_CONFIG_DEFAULTS { \
  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0001, 0x0006, 0x0000, CLUSTER_MASK_SERVER, 0x0000, 1, 65534, 0 }, /* Endpoint Id: 1, Cluster: On/off, Attribute: on/off */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0x0006, 0x0000, CLUSTER_MASK_SERVER, 0x0000, 1, 65534, 0 }, /* Endpoint Id: 2, Cluster: On/off, Attribute: on/off */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0003, 0x0006, 0x0000, CLUSTER_MASK_SERVER, 0x0000, 1, 65534, 0 }, /* Endpoint Id: 3, Cluster: On/off, Attribute: on/off */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0004, 0x0402, 0x0000, CLUSTER_MASK_SERVER, 0x0000, 0, 65534, 0 }, /* Endpoint Id: 4, Cluster: Temperature Measurement, Attribute: measured value */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0004, 0x0402, 0x0001, CLUSTER_MASK_SERVER, 0x0000, 0, 65534, 0 }, /* Endpoint Id: 4, Cluster: Temperature Measurement, Attribute: min measured value */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0004, 0x0402, 0x0002, CLUSTER_MASK_SERVER, 0x0000, 0, 65534, 0 }, /* Endpoint Id: 4, Cluster: Temperature Measurement, Attribute: max measured value */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0004, 0x0402, 0xFFFD, CLUSTER_MASK_SERVER, 0x0000, 0, 65534, 0 }, /* Endpoint Id: 4, Cluster: Temperature Measurement, Attribute: cluster revision */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0005, 0x0402, 0x0000, CLUSTER_MASK_SERVER, 0x0000, 0, 65534, 0 }, /* Endpoint Id: 5, Cluster: Temperature Measurement, Attribute: measured value */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0005, 0x0402, 0x0001, CLUSTER_MASK_SERVER, 0x0000, 0, 65534, 0 }, /* Endpoint Id: 5, Cluster: Temperature Measurement, Attribute: min measured value */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0005, 0x0402, 0x0002, CLUSTER_MASK_SERVER, 0x0000, 0, 65534, 0 }, /* Endpoint Id: 5, Cluster: Temperature Measurement, Attribute: max measured value */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0005, 0x0402, 0xFFFD, CLUSTER_MASK_SERVER, 0x0000, 0, 65534, 0 }, /* Endpoint Id: 5, Cluster: Temperature Measurement, Attribute: cluster revision */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0006, 0x0402, 0x0000, CLUSTER_MASK_SERVER, 0x0000, 0, 65534, 0 }, /* Endpoint Id: 6, Cluster: Temperature Measurement, Attribute: measured value */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0006, 0x0402, 0x0001, CLUSTER_MASK_SERVER, 0x0000, 0, 65534, 0 }, /* Endpoint Id: 6, Cluster: Temperature Measurement, Attribute: min measured value */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0006, 0x0402, 0x0002, CLUSTER_MASK_SERVER, 0x0000, 0, 65534, 0 }, /* Endpoint Id: 6, Cluster: Temperature Measurement, Attribute: max measured value */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0006, 0x0402, 0xFFFD, CLUSTER_MASK_SERVER, 0x0000, 0, 65534, 0 }, /* Endpoint Id: 6, Cluster: Temperature Measurement, Attribute: cluster revision */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0007, 0x0405, 0x0000, CLUSTER_MASK_SERVER, 0x0000, 0, 65534, 0 }, /* Endpoint Id: 7, Cluster: Relative Humidity Measurement, Attribute: measured value */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0007, 0x0405, 0x0001, CLUSTER_MASK_SERVER, 0x0000, 0, 65534, 0 }, /* Endpoint Id: 7, Cluster: Relative Humidity Measurement, Attribute: min measured value */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0007, 0x0405, 0x0002, CLUSTER_MASK_SERVER, 0x0000, 0, 65534, 0 }, /* Endpoint Id: 7, Cluster: Relative Humidity Measurement, Attribute: max measured value */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0007, 0x0405, 0xFFFD, CLUSTER_MASK_SERVER, 0x0000, 0, 65534, 0 }, /* Endpoint Id: 7, Cluster: Relative Humidity Measurement, Attribute: cluster revision */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0008, 0x0405, 0x0000, CLUSTER_MASK_SERVER, 0x0000, 0, 65534, 0 }, /* Endpoint Id: 8, Cluster: Relative Humidity Measurement, Attribute: measured value */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0008, 0x0405, 0x0001, CLUSTER_MASK_SERVER, 0x0000, 0, 65534, 0 }, /* Endpoint Id: 8, Cluster: Relative Humidity Measurement, Attribute: min measured value */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0008, 0x0405, 0x0002, CLUSTER_MASK_SERVER, 0x0000, 0, 65534, 0 }, /* Endpoint Id: 8, Cluster: Relative Humidity Measurement, Attribute: max measured value */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0008, 0x0405, 0xFFFD, CLUSTER_MASK_SERVER, 0x0000, 0, 65534, 0 }, /* Endpoint Id: 8, Cluster: Relative Humidity Measurement, Attribute: cluster revision */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0009, 0x0405, 0x0000, CLUSTER_MASK_SERVER, 0x0000, 0, 65534, 0 }, /* Endpoint Id: 9, Cluster: Relative Humidity Measurement, Attribute: measured value */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0009, 0x0405, 0x0001, CLUSTER_MASK_SERVER, 0x0000, 0, 65534, 0 }, /* Endpoint Id: 9, Cluster: Relative Humidity Measurement, Attribute: min measured value */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0009, 0x0405, 0x0002, CLUSTER_MASK_SERVER, 0x0000, 0, 65534, 0 }, /* Endpoint Id: 9, Cluster: Relative Humidity Measurement, Attribute: max measured value */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0009, 0x0405, 0xFFFD, CLUSTER_MASK_SERVER, 0x0000, 0, 65534, 0 }, /* Endpoint Id: 9, Cluster: Relative Humidity Measurement, Attribute: cluster revision */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x000D, 0x0006, 0x0000, CLUSTER_MASK_SERVER, 0x0000, 1, 65534, 0 }, /* Endpoint Id: 13, Cluster: On/off, Attribute: on/off */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x000D, 0x0008, 0x0000, CLUSTER_MASK_SERVER, 0x0000, 1, 65534, 0 }, /* Endpoint Id: 13, Cluster: Level Control, Attribute: current level */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x000E, 0x0006, 0x0000, CLUSTER_MASK_SERVER, 0x0000, 1, 65534, 0 }, /* Endpoint Id: 14, Cluster: On/off, Attribute: on/off */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x000E, 0x0008, 0x0000, CLUSTER_MASK_SERVER, 0x0000, 1, 65534, 0 }, /* Endpoint Id: 14, Cluster: Level Control, Attribute: current level */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x000F, 0x0006, 0x0000, CLUSTER_MASK_SERVER, 0x0000, 1, 65534, 0 }, /* Endpoint Id: 15, Cluster: On/off, Attribute: on/off */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x000F, 0x0008, 0x0000, CLUSTER_MASK_SERVER, 0x0000, 1, 65534, 0 }, /* Endpoint Id: 15, Cluster: Level Control, Attribute: current level */ \
	 } 

#define SL_ZIGBEE_ZCL_MANUFACTURER_CODE 0x1002
#define SL_ZIGBEE_AF_DEFAULT_RESPONSE_POLICY_ALWAYS

// All Enabled Clusters
#define ZCL_USING_BASIC_CLUSTER_SERVER
#define ZCL_USING_IDENTIFY_CLUSTER_SERVER
#define ZCL_USING_GROUPS_CLUSTER_SERVER
#define ZCL_USING_SCENES_CLUSTER_SERVER
#define ZCL_USING_ON_OFF_CLUSTER_CLIENT
#define ZCL_USING_ON_OFF_CLUSTER_SERVER
#define ZCL_USING_LEVEL_CONTROL_CLUSTER_CLIENT
#define ZCL_USING_LEVEL_CONTROL_CLUSTER_SERVER
#define ZCL_USING_TIME_CLUSTER_CLIENT
#define ZCL_USING_OTA_BOOTLOAD_CLUSTER_CLIENT
#define ZCL_USING_GREEN_POWER_CLUSTER_CLIENT
#define ZCL_USING_TEMP_MEASUREMENT_CLUSTER_SERVER
#define ZCL_USING_RELATIVE_HUMIDITY_MEASUREMENT_CLUSTER_SERVER
#define ZCL_USING_OCCUPANCY_SENSING_CLUSTER_CLIENT
#define ZCL_USING_ZLL_COMMISSIONING_CLUSTER_SERVER

// Cluster Counts
#define SL_ZIGBEE_ZCL_BASIC_CLUSTER_SERVER_ENDPOINT_COUNT (16)
#define SL_ZIGBEE_ZCL_IDENTIFY_CLUSTER_SERVER_ENDPOINT_COUNT (16)
#define SL_ZIGBEE_ZCL_GROUPS_CLUSTER_SERVER_ENDPOINT_COUNT (6)
#define SL_ZIGBEE_ZCL_SCENES_CLUSTER_SERVER_ENDPOINT_COUNT (6)
#define SL_ZIGBEE_ZCL_ON_OFF_CLUSTER_CLIENT_ENDPOINT_COUNT (3)
#define SL_ZIGBEE_ZCL_ON_OFF_CLUSTER_SERVER_ENDPOINT_COUNT (6)
#define SL_ZIGBEE_ZCL_LEVEL_CONTROL_CLUSTER_CLIENT_ENDPOINT_COUNT (3)
#define SL_ZIGBEE_ZCL_LEVEL_CONTROL_CLUSTER_SERVER_ENDPOINT_COUNT (3)
#define SL_ZIGBEE_ZCL_TIME_CLUSTER_CLIENT_ENDPOINT_COUNT (1)
#define SL_ZIGBEE_ZCL_OTA_BOOTLOAD_CLUSTER_CLIENT_ENDPOINT_COUNT (15)
#define SL_ZIGBEE_ZCL_GREEN_POWER_CLUSTER_CLIENT_ENDPOINT_COUNT (1)
#define SL_ZIGBEE_ZCL_TEMP_MEASUREMENT_CLUSTER_SERVER_ENDPOINT_COUNT (3)
#define SL_ZIGBEE_ZCL_RELATIVE_HUMIDITY_MEASUREMENT_CLUSTER_SERVER_ENDPOINT_COUNT (3)
#define SL_ZIGBEE_ZCL_OCCUPANCY_SENSING_CLUSTER_CLIENT_ENDPOINT_COUNT (6)
#define SL_ZIGBEE_ZCL_ZLL_COMMISSIONING_CLUSTER_SERVER_ENDPOINT_COUNT (6)

// All Enabled Cluster Attributes
#define ZCL_USING_BASIC_CLUSTER_VERSION_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_APPLICATION_VERSION_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_STACK_VERSION_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_HW_VERSION_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_MANUFACTURER_NAME_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_MODEL_IDENTIFIER_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_DATE_CODE_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_POWER_SOURCE_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_GENERIC_DEVICE_CLASS_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_GENERIC_DEVICE_TYPE_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_PRODUCT_CODE_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_PRODUCT_URL_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_SW_BUILD_ID_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_CLUSTER_REVISION_SERVER_ATTRIBUTE
#define ZCL_USING_IDENTIFY_CLUSTER_IDENTIFY_TIME_ATTRIBUTE
#define ZCL_USING_IDENTIFY_CLUSTER_CLUSTER_REVISION_SERVER_ATTRIBUTE
#define ZCL_USING_GROUPS_CLUSTER_GROUP_NAME_SUPPORT_ATTRIBUTE
#define ZCL_USING_GROUPS_CLUSTER_CLUSTER_REVISION_SERVER_ATTRIBUTE
#define ZCL_USING_SCENES_CLUSTER_SCENE_COUNT_ATTRIBUTE
#define ZCL_USING_SCENES_CLUSTER_CURRENT_SCENE_ATTRIBUTE
#define ZCL_USING_SCENES_CLUSTER_CURRENT_GROUP_ATTRIBUTE
#define ZCL_USING_SCENES_CLUSTER_SCENE_VALID_ATTRIBUTE
#define ZCL_USING_SCENES_CLUSTER_SCENE_NAME_SUPPORT_ATTRIBUTE
#define ZCL_USING_SCENES_CLUSTER_CLUSTER_REVISION_SERVER_ATTRIBUTE
#define ZCL_USING_ON_OFF_CLUSTER_CLUSTER_REVISION_CLIENT_ATTRIBUTE
#define ZCL_USING_ON_OFF_CLUSTER_ON_OFF_ATTRIBUTE
#define ZCL_USING_ON_OFF_CLUSTER_GLOBAL_SCENE_CONTROL_ATTRIBUTE
#define ZCL_USING_ON_OFF_CLUSTER_ON_TIME_ATTRIBUTE
#define ZCL_USING_ON_OFF_CLUSTER_OFF_WAIT_TIME_ATTRIBUTE
#define ZCL_USING_ON_OFF_CLUSTER_START_UP_ON_OFF_ATTRIBUTE
#define ZCL_USING_ON_OFF_CLUSTER_CLUSTER_REVISION_SERVER_ATTRIBUTE
#define ZCL_USING_LEVEL_CONTROL_CLUSTER_CLUSTER_REVISION_CLIENT_ATTRIBUTE
#define ZCL_USING_LEVEL_CONTROL_CLUSTER_CURRENT_LEVEL_ATTRIBUTE
#define ZCL_USING_LEVEL_CONTROL_CLUSTER_LEVEL_CONTROL_REMAINING_TIME_ATTRIBUTE
#define ZCL_USING_LEVEL_CONTROL_CLUSTER_OPTIONS_ATTRIBUTE
#define ZCL_USING_LEVEL_CONTROL_CLUSTER_ON_OFF_TRANSITION_TIME_ATTRIBUTE
#define ZCL_USING_LEVEL_CONTROL_CLUSTER_ON_LEVEL_ATTRIBUTE
#define ZCL_USING_LEVEL_CONTROL_CLUSTER_DEFAULT_MOVE_RATE_ATTRIBUTE
#define ZCL_USING_LEVEL_CONTROL_CLUSTER_START_UP_CURRENT_LEVEL_ATTRIBUTE
#define ZCL_USING_LEVEL_CONTROL_CLUSTER_CLUSTER_REVISION_SERVER_ATTRIBUTE
#define ZCL_USING_TIME_CLUSTER_CLUSTER_REVISION_CLIENT_ATTRIBUTE
#define ZCL_USING_OTA_BOOTLOAD_CLUSTER_UPGRADE_SERVER_ID_ATTRIBUTE
#define ZCL_USING_OTA_BOOTLOAD_CLUSTER_FILE_OFFSET_ATTRIBUTE
#define ZCL_USING_OTA_BOOTLOAD_CLUSTER_CURRENT_FILE_VERSION_ATTRIBUTE
#define ZCL_USING_OTA_BOOTLOAD_CLUSTER_IMAGE_UPGRADE_STATUS_ATTRIBUTE
#define ZCL_USING_OTA_BOOTLOAD_CLUSTER_CLUSTER_REVISION_CLIENT_ATTRIBUTE
#define ZCL_USING_GREEN_POWER_CLUSTER_GP_CLIENT_GPP_MAX_PROXY_TABLE_ENTRIES_ATTRIBUTE
#define ZCL_USING_GREEN_POWER_CLUSTER_GP_CLIENT_PROXY_TABLE_ATTRIBUTE
#define ZCL_USING_GREEN_POWER_CLUSTER_GP_CLIENT_GPP_FUNCTIONALITY_ATTRIBUTE
#define ZCL_USING_GREEN_POWER_CLUSTER_GP_CLIENT_GPP_ACTIVE_FUNCTIONALITY_ATTRIBUTE
#define ZCL_USING_GREEN_POWER_CLUSTER_GP_CLIENT_GP_SHARED_SECURITY_KEY_TYPE_ATTRIBUTE
#define ZCL_USING_GREEN_POWER_CLUSTER_GP_CLIENT_GP_SHARED_SECURITY_KEY_ATTRIBUTE
#define ZCL_USING_GREEN_POWER_CLUSTER_GP_CLIENT_GP_LINK_KEY_ATTRIBUTE
#define ZCL_USING_GREEN_POWER_CLUSTER_CLUSTER_REVISION_CLIENT_ATTRIBUTE
#define ZCL_USING_TEMP_MEASUREMENT_CLUSTER_TEMP_MEASURED_VALUE_ATTRIBUTE
#define ZCL_USING_TEMP_MEASUREMENT_CLUSTER_TEMP_MIN_MEASURED_VALUE_ATTRIBUTE
#define ZCL_USING_TEMP_MEASUREMENT_CLUSTER_TEMP_MAX_MEASURED_VALUE_ATTRIBUTE
#define ZCL_USING_TEMP_MEASUREMENT_CLUSTER_CLUSTER_REVISION_SERVER_ATTRIBUTE
#define ZCL_USING_RELATIVE_HUMIDITY_MEASUREMENT_CLUSTER_RELATIVE_HUMIDITY_MEASURED_VALUE_ATTRIBUTE
#define ZCL_USING_RELATIVE_HUMIDITY_MEASUREMENT_CLUSTER_RELATIVE_HUMIDITY_MIN_MEASURED_VALUE_ATTRIBUTE
#define ZCL_USING_RELATIVE_HUMIDITY_MEASUREMENT_CLUSTER_RELATIVE_HUMIDITY_MAX_MEASURED_VALUE_ATTRIBUTE
#define ZCL_USING_RELATIVE_HUMIDITY_MEASUREMENT_CLUSTER_CLUSTER_REVISION_SERVER_ATTRIBUTE
#define ZCL_USING_OCCUPANCY_SENSING_CLUSTER_CLUSTER_REVISION_CLIENT_ATTRIBUTE
#define ZCL_USING_ZLL_COMMISSIONING_CLUSTER_CLUSTER_REVISION_SERVER_ATTRIBUTE

#define SL_ZIGBEE_AF_SUPPORT_COMMAND_DISCOVERY

/* Format: Zigbee Cluster Code, Zigbee Cluster Mfg Code, Matter Cluster Code, Matter Cluster Mfg Code, Zigbee Attribute Code, Zigbee Attribute Mfg Code, Zigbee Attribute Type Identifier, Matter Attribute Code, Matter Attribute Mfg Code, Matter Attribute Type Identifier */
#define GENERATED_MULTI_PROTOCOL_ATTRIBUTE_MAPPING \
{ \
  { 0x0006, 0x0000, 0x0006, 0x0000, 0x0000, 0x0000, 16, 0x0000, 0x0000, 16 }, /* 0, Zigbee Cluster: On/off, Matter Cluster: On/Off, Zigbee Attribute: on/off, Matter Attribute: OnOff */ \
  { 0x0006, 0x0000, 0x0006, 0x0000, 0x4003, 0x0000, 48, 0x4003, 0x0000, 48 }, /* 1, Zigbee Cluster: On/off, Matter Cluster: On/Off, Zigbee Attribute: start up on off, Matter Attribute: StartUpOnOff */ \
  { 0x0008, 0x0000, 0x0008, 0x0000, 0x0000, 0x0000, 32, 0x0000, 0x0000, 32 }, /* 2, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: current level, Matter Attribute: CurrentLevel */ \
  { 0x0008, 0x0000, 0x0008, 0x0000, 0x0001, 0x0000, 33, 0x0001, 0x0000, 33 }, /* 3, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: remaining time, Matter Attribute: RemainingTime */ \
  { 0x0008, 0x0000, 0x0008, 0x0000, 0x0002, 0x0000, 32, 0x0002, 0x0000, 32 }, /* 4, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: min level, Matter Attribute: MinLevel */ \
  { 0x0008, 0x0000, 0x0008, 0x0000, 0x0003, 0x0000, 32, 0x0003, 0x0000, 32 }, /* 5, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: max level, Matter Attribute: MaxLevel */ \
  { 0x0008, 0x0000, 0x0008, 0x0000, 0x0004, 0x0000, 33, 0x0004, 0x0000, 33 }, /* 6, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: current frequency, Matter Attribute: CurrentFrequency */ \
  { 0x0008, 0x0000, 0x0008, 0x0000, 0x0005, 0x0000, 33, 0x0005, 0x0000, 33 }, /* 7, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: min frequency, Matter Attribute: MinFrequency */ \
  { 0x0008, 0x0000, 0x0008, 0x0000, 0x0006, 0x0000, 33, 0x0006, 0x0000, 33 }, /* 8, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: max frequency, Matter Attribute: MaxFrequency */ \
  { 0x0008, 0x0000, 0x0008, 0x0000, 0x000F, 0x0000, 24, 0x000F, 0x0000, 24 }, /* 9, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: options, Matter Attribute: Options */ \
  { 0x0008, 0x0000, 0x0008, 0x0000, 0x0010, 0x0000, 33, 0x0010, 0x0000, 33 }, /* 10, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: on off transition time, Matter Attribute: OnOffTransitionTime */ \
  { 0x0008, 0x0000, 0x0008, 0x0000, 0x0011, 0x0000, 32, 0x0011, 0x0000, 32 }, /* 11, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: on level, Matter Attribute: OnLevel */ \
  { 0x0008, 0x0000, 0x0008, 0x0000, 0x0012, 0x0000, 33, 0x0012, 0x0000, 33 }, /* 12, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: on transition time, Matter Attribute: OnTransitionTime */ \
  { 0x0008, 0x0000, 0x0008, 0x0000, 0x0013, 0x0000, 33, 0x0013, 0x0000, 33 }, /* 13, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: off transition time, Matter Attribute: OffTransitionTime */ \
  { 0x0008, 0x0000, 0x0008, 0x0000, 0x0014, 0x0000, 32, 0x0014, 0x0000, 32 }, /* 14, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: default move rate, Matter Attribute: DefaultMoveRate */ \
  { 0x0008, 0x0000, 0x0008, 0x0000, 0x4000, 0x0000, 32, 0x4000, 0x0000, 32 }, /* 15, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: start up current level, Matter Attribute: StartUpCurrentLevel */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0000, 0x0000, 32, 0x0000, 0x0000, 32 }, /* 16, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: current hue, Matter Attribute: CurrentHue */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0001, 0x0000, 32, 0x0001, 0x0000, 32 }, /* 17, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: current saturation, Matter Attribute: CurrentSaturation */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0002, 0x0000, 33, 0x0002, 0x0000, 33 }, /* 18, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: remaining time, Matter Attribute: RemainingTime */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0003, 0x0000, 33, 0x0003, 0x0000, 33 }, /* 19, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: current x, Matter Attribute: CurrentX */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0004, 0x0000, 33, 0x0004, 0x0000, 33 }, /* 20, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: current y, Matter Attribute: CurrentY */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0005, 0x0000, 48, 0x0005, 0x0000, 48 }, /* 21, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: drift compensation, Matter Attribute: DriftCompensation */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0006, 0x0000, 66, 0x0006, 0x0000, 66 }, /* 22, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: compensation text, Matter Attribute: CompensationText */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0007, 0x0000, 33, 0x0007, 0x0000, 33 }, /* 23, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color temperature, Matter Attribute: ColorTemperatureMireds */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0008, 0x0000, 48, 0x0008, 0x0000, 48 }, /* 24, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color mode, Matter Attribute: ColorMode */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x000F, 0x0000, 24, 0x000F, 0x0000, 24 }, /* 25, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color control options, Matter Attribute: Options */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0010, 0x0000, 32, 0x0010, 0x0000, 32 }, /* 26, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: number of primaries, Matter Attribute: NumberOfPrimaries */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0011, 0x0000, 33, 0x0011, 0x0000, 33 }, /* 27, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 1 x, Matter Attribute: Primary1X */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0012, 0x0000, 33, 0x0012, 0x0000, 33 }, /* 28, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 1 y, Matter Attribute: Primary1Y */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0013, 0x0000, 32, 0x0013, 0x0000, 32 }, /* 29, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 1 intensity, Matter Attribute: Primary1Intensity */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0015, 0x0000, 33, 0x0015, 0x0000, 33 }, /* 30, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 2 x, Matter Attribute: Primary2X */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0016, 0x0000, 33, 0x0016, 0x0000, 33 }, /* 31, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 2 y, Matter Attribute: Primary2Y */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0017, 0x0000, 32, 0x0017, 0x0000, 32 }, /* 32, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 2 intensity, Matter Attribute: Primary2Intensity */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0019, 0x0000, 33, 0x0019, 0x0000, 33 }, /* 33, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 3 x, Matter Attribute: Primary3X */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x001A, 0x0000, 33, 0x001A, 0x0000, 33 }, /* 34, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 3 y, Matter Attribute: Primary3Y */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x001B, 0x0000, 32, 0x001B, 0x0000, 32 }, /* 35, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 3 intensity, Matter Attribute: Primary3Intensity */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0020, 0x0000, 33, 0x0020, 0x0000, 33 }, /* 36, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 4 x, Matter Attribute: Primary4X */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0021, 0x0000, 33, 0x0021, 0x0000, 33 }, /* 37, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 4 y, Matter Attribute: Primary4Y */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0022, 0x0000, 32, 0x0022, 0x0000, 32 }, /* 38, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 4 intensity, Matter Attribute: Primary4Intensity */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0024, 0x0000, 33, 0x0024, 0x0000, 33 }, /* 39, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 5 x, Matter Attribute: Primary5X */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0025, 0x0000, 33, 0x0025, 0x0000, 33 }, /* 40, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 5 y, Matter Attribute: Primary5Y */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0026, 0x0000, 32, 0x0026, 0x0000, 32 }, /* 41, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 5 intensity, Matter Attribute: Primary5Intensity */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0028, 0x0000, 33, 0x0028, 0x0000, 33 }, /* 42, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 6 x, Matter Attribute: Primary6X */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0029, 0x0000, 33, 0x0029, 0x0000, 33 }, /* 43, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 6 y, Matter Attribute: Primary6Y */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x002A, 0x0000, 32, 0x002A, 0x0000, 32 }, /* 44, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 6 intensity, Matter Attribute: Primary6Intensity */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0030, 0x0000, 33, 0x0030, 0x0000, 33 }, /* 45, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: white point x, Matter Attribute: WhitePointX */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0031, 0x0000, 33, 0x0031, 0x0000, 33 }, /* 46, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: white point y, Matter Attribute: WhitePointY */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0032, 0x0000, 33, 0x0032, 0x0000, 33 }, /* 47, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color point r x, Matter Attribute: ColorPointRX */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0033, 0x0000, 33, 0x0033, 0x0000, 33 }, /* 48, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color point r y, Matter Attribute: ColorPointRY */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0034, 0x0000, 32, 0x0034, 0x0000, 32 }, /* 49, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color point r intensity, Matter Attribute: ColorPointRIntensity */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0036, 0x0000, 33, 0x0036, 0x0000, 33 }, /* 50, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color point g x, Matter Attribute: ColorPointGX */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0037, 0x0000, 33, 0x0037, 0x0000, 33 }, /* 51, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color point g y, Matter Attribute: ColorPointGY */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x0038, 0x0000, 32, 0x0038, 0x0000, 32 }, /* 52, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color point g intensity, Matter Attribute: ColorPointGIntensity */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x003A, 0x0000, 33, 0x003A, 0x0000, 33 }, /* 53, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color point b x, Matter Attribute: ColorPointBX */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x003B, 0x0000, 33, 0x003B, 0x0000, 33 }, /* 54, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color point b y, Matter Attribute: ColorPointBY */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x003C, 0x0000, 32, 0x003C, 0x0000, 32 }, /* 55, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color point b intensity, Matter Attribute: ColorPointBIntensity */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x4000, 0x0000, 33, 0x4000, 0x0000, 33 }, /* 56, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: enhanced current hue, Matter Attribute: EnhancedCurrentHue */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x4001, 0x0000, 48, 0x4001, 0x0000, 48 }, /* 57, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: enhanced color mode, Matter Attribute: EnhancedColorMode */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x4002, 0x0000, 32, 0x4002, 0x0000, 32 }, /* 58, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color loop active, Matter Attribute: ColorLoopActive */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x4003, 0x0000, 32, 0x4003, 0x0000, 32 }, /* 59, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color loop direction, Matter Attribute: ColorLoopDirection */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x4004, 0x0000, 33, 0x4004, 0x0000, 33 }, /* 60, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color loop time, Matter Attribute: ColorLoopTime */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x4005, 0x0000, 33, 0x4005, 0x0000, 33 }, /* 61, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color loop start enhanced hue, Matter Attribute: ColorLoopStartEnhancedHue */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x4006, 0x0000, 33, 0x4006, 0x0000, 33 }, /* 62, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color loop stored enhanced hue, Matter Attribute: ColorLoopStoredEnhancedHue */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x400A, 0x0000, 25, 0x400A, 0x0000, 25 }, /* 63, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color capabilities, Matter Attribute: ColorCapabilities */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x400B, 0x0000, 33, 0x400B, 0x0000, 33 }, /* 64, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color temp physical min, Matter Attribute: ColorTempPhysicalMinMireds */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x400C, 0x0000, 33, 0x400C, 0x0000, 33 }, /* 65, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color temp physical max, Matter Attribute: ColorTempPhysicalMaxMireds */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x400D, 0x0000, 33, 0x400D, 0x0000, 33 }, /* 66, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: couple color temp to level min-mireds, Matter Attribute: CoupleColorTempToLevelMinMireds */ \
  { 0x0300, 0x0000, 0x0300, 0x0000, 0x4010, 0x0000, 33, 0x4010, 0x0000, 33 } /* 67, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: start up color temperature mireds, Matter Attribute: StartUpColorTemperatureMireds */ \
}


#endif // SILABS_AF_ENDPOINT_CONFIG