/*
 * This file is part of the Silicon Labs Arduino Core
 *
 * The MIT License (MIT)
 *
 * Copyright 2024 Silicon Laboratories Inc. www.silabs.com
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

// This file is generated by ZCL Advanced Platform generator. Please don't edit manually.

// Enclosing macro to prevent multiple inclusion
#ifndef SILABS_PRINT_CLUSTER
#define SILABS_PRINT_CLUSTER


// This is the mapping of IDs to cluster names assuming a format according
// to the "sl_zigbee_af_cluster_name_t" defined in the ZCL header.
// The names of clusters that are not present, are removed.

  #define SILABS_PRINTCLUSTER_BASIC_CLUSTER { ZCL_BASIC_CLUSTER_ID, 0x0000, "Basic" },
  #define SILABS_PRINTCLUSTER_GREEN_POWER_CLUSTER { ZCL_GREEN_POWER_CLUSTER_ID, 0x0000, "Green Power" },
  #define SILABS_PRINTCLUSTER_GROUPS_CLUSTER { ZCL_GROUPS_CLUSTER_ID, 0x0000, "Groups" },
  #define SILABS_PRINTCLUSTER_IDENTIFY_CLUSTER { ZCL_IDENTIFY_CLUSTER_ID, 0x0000, "Identify" },
  #define SILABS_PRINTCLUSTER_LEVEL_CONTROL_CLUSTER { ZCL_LEVEL_CONTROL_CLUSTER_ID, 0x0000, "Level Control" },
  #define SILABS_PRINTCLUSTER_OCCUPANCY_SENSING_CLUSTER { ZCL_OCCUPANCY_SENSING_CLUSTER_ID, 0x0000, "Occupancy Sensing" },
  #define SILABS_PRINTCLUSTER_ON_OFF_CLUSTER { ZCL_ON_OFF_CLUSTER_ID, 0x0000, "On/off" },
  #define SILABS_PRINTCLUSTER_OTA_BOOTLOAD_CLUSTER { ZCL_OTA_BOOTLOAD_CLUSTER_ID, 0x0000, "Over the Air Bootloading" },
  #define SILABS_PRINTCLUSTER_SCENES_CLUSTER { ZCL_SCENES_CLUSTER_ID, 0x0000, "Scenes" },
  #define SILABS_PRINTCLUSTER_ZLL_COMMISSIONING_CLUSTER { ZCL_ZLL_COMMISSIONING_CLUSTER_ID, 0x0000, "ZLL Commissioning" },

#define CLUSTER_IDS_TO_NAMES \
  SILABS_PRINTCLUSTER_BASIC_CLUSTER \
  SILABS_PRINTCLUSTER_GREEN_POWER_CLUSTER \
  SILABS_PRINTCLUSTER_GROUPS_CLUSTER \
  SILABS_PRINTCLUSTER_IDENTIFY_CLUSTER \
  SILABS_PRINTCLUSTER_LEVEL_CONTROL_CLUSTER \
  SILABS_PRINTCLUSTER_OCCUPANCY_SENSING_CLUSTER \
  SILABS_PRINTCLUSTER_ON_OFF_CLUSTER \
  SILABS_PRINTCLUSTER_OTA_BOOTLOAD_CLUSTER \
  SILABS_PRINTCLUSTER_SCENES_CLUSTER \
  SILABS_PRINTCLUSTER_ZLL_COMMISSIONING_CLUSTER \

#endif // SILABS_PRINT_CLUSTER
