/***************************************************************************//**
 * @file
 * @brief This file contains definitions for storing ZCL attributes
 * in NVM tokens.
 *******************************************************************************
 * # License
 * <b>Copyright 2024 Silicon Laboratories Inc. www.silabs.com</b>
 *******************************************************************************
 *
 * The licensor of this software is Silicon Laboratories Inc. Your use of this
 * software is governed by the terms of Silicon Labs Master Software License
 * Agreement (MSLA) available at
 * www.silabs.com/about-us/legal/master-software-license-agreement. This
 * software is distributed to you in Source Code format and is governed by the
 * sections of the MSLA applicable to Source Code.
 *
 ******************************************************************************/

// This file is generated by ZCL Advanced Platform generator. Please don't edit manually.

#include "af-types.h"

#define NUM_PERSISTED_ZCL_ATTRIBUTES (6)


// Identifier tags for tokens
// Creator for attribute: on/off, endpoint: 1
#define CREATOR_ON_OFF_1 0xB000
#define NVM3KEY_ON_OFF_1 (NVM3KEY_DOMAIN_ZIGBEE | 0xB000)
// Creator for attribute: start up on off, endpoint: 1
#define CREATOR_START_UP_ON_OFF_1 0xB001
#define NVM3KEY_START_UP_ON_OFF_1 (NVM3KEY_DOMAIN_ZIGBEE | 0xB001)
// Creator for attribute: on/off, endpoint: 2
#define CREATOR_ON_OFF_2 0xB002
#define NVM3KEY_ON_OFF_2 (NVM3KEY_DOMAIN_ZIGBEE | 0xB002)
// Creator for attribute: start up on off, endpoint: 2
#define CREATOR_START_UP_ON_OFF_2 0xB003
#define NVM3KEY_START_UP_ON_OFF_2 (NVM3KEY_DOMAIN_ZIGBEE | 0xB003)
// Creator for attribute: on/off, endpoint: 3
#define CREATOR_ON_OFF_3 0xB004
#define NVM3KEY_ON_OFF_3 (NVM3KEY_DOMAIN_ZIGBEE | 0xB004)
// Creator for attribute: start up on off, endpoint: 3
#define CREATOR_START_UP_ON_OFF_3 0xB005
#define NVM3KEY_START_UP_ON_OFF_3 (NVM3KEY_DOMAIN_ZIGBEE | 0xB005)


// Types for the tokens
#ifdef DEFINETYPES
typedef uint8_t tokType_on_off;
        typedef uint8_t tokType_start_up_on_off;
        #endif // DEFINETYPES

// Actual token definitions
#ifdef DEFINETOKENS

DEFINE_BASIC_TOKEN(ON_OFF_1, tokType_on_off, 0x0)
DEFINE_BASIC_TOKEN(START_UP_ON_OFF_1, tokType_start_up_on_off, 0xFF)
DEFINE_BASIC_TOKEN(ON_OFF_2, tokType_on_off, 0x0)
DEFINE_BASIC_TOKEN(START_UP_ON_OFF_2, tokType_start_up_on_off, 0xFF)
DEFINE_BASIC_TOKEN(ON_OFF_3, tokType_on_off, 0x0)
DEFINE_BASIC_TOKEN(START_UP_ON_OFF_3, tokType_start_up_on_off, 0xFF)
#endif // DEFINETOKENS

// Macro snippet that loads all the attributes from tokens
#define GENERATED_TOKEN_LOADER(endpoint) do { \
  uint8_t ptr[1]; \
  uint8_t curNetwork = sl_zigbee_get_current_network(); \
  uint8_t epNetwork; \
  epNetwork = sl_zigbee_af_network_index_from_endpoint(1); \
  if(1 == (endpoint) || (SL_ZIGBEE_BROADCAST_ENDPOINT == (endpoint) && epNetwork == curNetwork)) { \
    halCommonGetToken((tokType_on_off *)ptr, TOKEN_ON_OFF_1); \
    sli_zigbee_af_write_attribute(1, ZCL_ON_OFF_CLUSTER_ID, ZCL_ON_OFF_ATTRIBUTE_ID, CLUSTER_MASK_SERVER, SL_ZIGBEE_AF_NULL_MANUFACTURER_CODE, (uint8_t*)ptr, ZCL_BOOLEAN_ATTRIBUTE_TYPE, true, false, false); \
    halCommonGetToken((tokType_start_up_on_off *)ptr, TOKEN_START_UP_ON_OFF_1); \
    sli_zigbee_af_write_attribute(1, ZCL_ON_OFF_CLUSTER_ID, ZCL_START_UP_ON_OFF_ATTRIBUTE_ID, CLUSTER_MASK_SERVER, SL_ZIGBEE_AF_NULL_MANUFACTURER_CODE, (uint8_t*)ptr, ZCL_ENUM8_ATTRIBUTE_TYPE, true, false, false); \
  } \
  epNetwork = sl_zigbee_af_network_index_from_endpoint(2); \
  if(2 == (endpoint) || (SL_ZIGBEE_BROADCAST_ENDPOINT == (endpoint) && epNetwork == curNetwork)) { \
    halCommonGetToken((tokType_on_off *)ptr, TOKEN_ON_OFF_2); \
    sli_zigbee_af_write_attribute(2, ZCL_ON_OFF_CLUSTER_ID, ZCL_ON_OFF_ATTRIBUTE_ID, CLUSTER_MASK_SERVER, SL_ZIGBEE_AF_NULL_MANUFACTURER_CODE, (uint8_t*)ptr, ZCL_BOOLEAN_ATTRIBUTE_TYPE, true, false, false); \
    halCommonGetToken((tokType_start_up_on_off *)ptr, TOKEN_START_UP_ON_OFF_2); \
    sli_zigbee_af_write_attribute(2, ZCL_ON_OFF_CLUSTER_ID, ZCL_START_UP_ON_OFF_ATTRIBUTE_ID, CLUSTER_MASK_SERVER, SL_ZIGBEE_AF_NULL_MANUFACTURER_CODE, (uint8_t*)ptr, ZCL_ENUM8_ATTRIBUTE_TYPE, true, false, false); \
  } \
  epNetwork = sl_zigbee_af_network_index_from_endpoint(3); \
  if(3 == (endpoint) || (SL_ZIGBEE_BROADCAST_ENDPOINT == (endpoint) && epNetwork == curNetwork)) { \
    halCommonGetToken((tokType_on_off *)ptr, TOKEN_ON_OFF_3); \
    sli_zigbee_af_write_attribute(3, ZCL_ON_OFF_CLUSTER_ID, ZCL_ON_OFF_ATTRIBUTE_ID, CLUSTER_MASK_SERVER, SL_ZIGBEE_AF_NULL_MANUFACTURER_CODE, (uint8_t*)ptr, ZCL_BOOLEAN_ATTRIBUTE_TYPE, true, false, false); \
    halCommonGetToken((tokType_start_up_on_off *)ptr, TOKEN_START_UP_ON_OFF_3); \
    sli_zigbee_af_write_attribute(3, ZCL_ON_OFF_CLUSTER_ID, ZCL_START_UP_ON_OFF_ATTRIBUTE_ID, CLUSTER_MASK_SERVER, SL_ZIGBEE_AF_NULL_MANUFACTURER_CODE, (uint8_t*)ptr, ZCL_ENUM8_ATTRIBUTE_TYPE, true, false, false); \
  } \
} while (false)

// Macro snippet that saves the attribute to token
#define GENERATED_TOKEN_SAVER do { \
  uint8_t allZeroData[1]; \
  memset(allZeroData, 0, 1);  \
  if ( data == NULL ) { data = allZeroData; } \
if ( 1 == endpoint ) { \
    if ( 0x0006 == clusterId ) { \
if ( 0x0000 == metadata->attributeId && 0x0000 == sl_zigbee_af_get_mfg_code(metadata) && !sl_zigbee_af_attribute_is_client(metadata) ) \
          halCommonSetToken(TOKEN_ON_OFF_1, data); \
if ( 0x4003 == metadata->attributeId && 0x0000 == sl_zigbee_af_get_mfg_code(metadata) && !sl_zigbee_af_attribute_is_client(metadata) ) \
          halCommonSetToken(TOKEN_START_UP_ON_OFF_1, data); \
    } \
} \
if ( 2 == endpoint ) { \
    if ( 0x0006 == clusterId ) { \
if ( 0x0000 == metadata->attributeId && 0x0000 == sl_zigbee_af_get_mfg_code(metadata) && !sl_zigbee_af_attribute_is_client(metadata) ) \
          halCommonSetToken(TOKEN_ON_OFF_2, data); \
if ( 0x4003 == metadata->attributeId && 0x0000 == sl_zigbee_af_get_mfg_code(metadata) && !sl_zigbee_af_attribute_is_client(metadata) ) \
          halCommonSetToken(TOKEN_START_UP_ON_OFF_2, data); \
    } \
} \
if ( 3 == endpoint ) { \
    if ( 0x0006 == clusterId ) { \
if ( 0x0000 == metadata->attributeId && 0x0000 == sl_zigbee_af_get_mfg_code(metadata) && !sl_zigbee_af_attribute_is_client(metadata) ) \
          halCommonSetToken(TOKEN_ON_OFF_3, data); \
if ( 0x4003 == metadata->attributeId && 0x0000 == sl_zigbee_af_get_mfg_code(metadata) && !sl_zigbee_af_attribute_is_client(metadata) ) \
          halCommonSetToken(TOKEN_START_UP_ON_OFF_3, data); \
    } \
} \
} while (false)
